language:
- php
- c

php:
- 5.3
- 5.4
- 5.5
- 5.6

before_script:
- sudo apt-get update
- sudo apt-get install apache2 php5-dev libpcre3-dev gcc make
- cd build
- ./install 
- echo "extension = smce.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- sudo service apache2 restart
- cd ..
- cd test

script:  phpunit --configuration phpunit.xml --process-isolation


notifications:
  email: false
