smce.lo: /var/www/html/smceframework2/zephir/smce/ext/smce.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/smce.c -o smce.lo 
kernel/main.lo: /var/www/html/smceframework2/zephir/smce/ext/kernel/main.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/kernel/main.c -o kernel/main.lo 
kernel/memory.lo: /var/www/html/smceframework2/zephir/smce/ext/kernel/memory.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/kernel/memory.c -o kernel/memory.lo 
kernel/exception.lo: /var/www/html/smceframework2/zephir/smce/ext/kernel/exception.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/kernel/exception.c -o kernel/exception.lo 
kernel/hash.lo: /var/www/html/smceframework2/zephir/smce/ext/kernel/hash.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/kernel/hash.c -o kernel/hash.lo 
kernel/debug.lo: /var/www/html/smceframework2/zephir/smce/ext/kernel/debug.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/kernel/debug.c -o kernel/debug.lo 
kernel/backtrace.lo: /var/www/html/smceframework2/zephir/smce/ext/kernel/backtrace.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/kernel/backtrace.c -o kernel/backtrace.lo 
kernel/object.lo: /var/www/html/smceframework2/zephir/smce/ext/kernel/object.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/kernel/object.c -o kernel/object.lo 
kernel/array.lo: /var/www/html/smceframework2/zephir/smce/ext/kernel/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/kernel/array.c -o kernel/array.lo 
kernel/extended/array.lo: /var/www/html/smceframework2/zephir/smce/ext/kernel/extended/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/kernel/extended/array.c -o kernel/extended/array.lo 
kernel/string.lo: /var/www/html/smceframework2/zephir/smce/ext/kernel/string.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/kernel/string.c -o kernel/string.lo 
kernel/fcall.lo: /var/www/html/smceframework2/zephir/smce/ext/kernel/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/kernel/fcall.c -o kernel/fcall.lo 
kernel/require.lo: /var/www/html/smceframework2/zephir/smce/ext/kernel/require.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/kernel/require.c -o kernel/require.lo 
kernel/file.lo: /var/www/html/smceframework2/zephir/smce/ext/kernel/file.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/kernel/file.c -o kernel/file.lo 
kernel/operators.lo: /var/www/html/smceframework2/zephir/smce/ext/kernel/operators.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/kernel/operators.c -o kernel/operators.lo 
kernel/concat.lo: /var/www/html/smceframework2/zephir/smce/ext/kernel/concat.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/kernel/concat.c -o kernel/concat.lo 
kernel/variables.lo: /var/www/html/smceframework2/zephir/smce/ext/kernel/variables.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/kernel/variables.c -o kernel/variables.lo 
kernel/filter.lo: /var/www/html/smceframework2/zephir/smce/ext/kernel/filter.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/kernel/filter.c -o kernel/filter.lo 
kernel/iterator.lo: /var/www/html/smceframework2/zephir/smce/ext/kernel/iterator.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/kernel/iterator.c -o kernel/iterator.lo 
kernel/exit.lo: /var/www/html/smceframework2/zephir/smce/ext/kernel/exit.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/kernel/exit.c -o kernel/exit.lo 
smce/app.lo: /var/www/html/smceframework2/zephir/smce/ext/smce/app.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/smce/app.zep.c -o smce/app.lo 
smce/components/collection.lo: /var/www/html/smceframework2/zephir/smce/ext/smce/components/collection.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/smce/components/collection.zep.c -o smce/components/collection.lo 
smce/components/output.lo: /var/www/html/smceframework2/zephir/smce/ext/smce/components/output.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/smce/components/output.zep.c -o smce/components/output.lo 
smce/components/session.lo: /var/www/html/smceframework2/zephir/smce/ext/smce/components/session.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/smce/components/session.zep.c -o smce/components/session.lo 
smce/core/di.lo: /var/www/html/smceframework2/zephir/smce/ext/smce/core/di.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/smce/core/di.zep.c -o smce/core/di.lo 
smce/core/di/diadapter.lo: /var/www/html/smceframework2/zephir/smce/ext/smce/core/di/diadapter.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/smce/core/di/diadapter.zep.c -o smce/core/di/diadapter.lo 
smce/core/di/dicache.lo: /var/www/html/smceframework2/zephir/smce/ext/smce/core/di/dicache.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/smce/core/di/dicache.zep.c -o smce/core/di/dicache.lo 
smce/core/di/singleton.lo: /var/www/html/smceframework2/zephir/smce/ext/smce/core/di/singleton.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/smce/core/di/singleton.zep.c -o smce/core/di/singleton.lo 
smce/core/eventmanager.lo: /var/www/html/smceframework2/zephir/smce/ext/smce/core/eventmanager.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/smce/core/eventmanager.zep.c -o smce/core/eventmanager.lo 
smce/core/loader.lo: /var/www/html/smceframework2/zephir/smce/ext/smce/core/loader.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/smce/core/loader.zep.c -o smce/core/loader.lo 
smce/core/smceframework.lo: /var/www/html/smceframework2/zephir/smce/ext/smce/core/smceframework.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/smce/core/smceframework.zep.c -o smce/core/smceframework.lo 
smce/driver/memcache.lo: /var/www/html/smceframework2/zephir/smce/ext/smce/driver/memcache.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/smce/driver/memcache.zep.c -o smce/driver/memcache.lo 
smce/driver/redis.lo: /var/www/html/smceframework2/zephir/smce/ext/smce/driver/redis.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/smce/driver/redis.zep.c -o smce/driver/redis.lo 
smce/http/httpexception.lo: /var/www/html/smceframework2/zephir/smce/ext/smce/http/httpexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/smce/http/httpexception.zep.c -o smce/http/httpexception.lo 
smce/http/response.lo: /var/www/html/smceframework2/zephir/smce/ext/smce/http/response.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/smce/http/response.zep.c -o smce/http/response.lo 
smce/mvc/acl.lo: /var/www/html/smceframework2/zephir/smce/ext/smce/mvc/acl.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/smce/mvc/acl.zep.c -o smce/mvc/acl.lo 
smce/mvc/router.lo: /var/www/html/smceframework2/zephir/smce/ext/smce/mvc/router.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/smce/mvc/router.zep.c -o smce/mvc/router.lo 
smce/mvc/router/exception.lo: /var/www/html/smceframework2/zephir/smce/ext/smce/mvc/router/exception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/smce/mvc/router/exception.zep.c -o smce/mvc/router/exception.lo 
smce/mvc/router/route.lo: /var/www/html/smceframework2/zephir/smce/ext/smce/mvc/router/route.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/smce/mvc/router/route.zep.c -o smce/mvc/router/route.lo 
smce/mvc/url.lo: /var/www/html/smceframework2/zephir/smce/ext/smce/mvc/url.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/smce/mvc/url.zep.c -o smce/mvc/url.lo 
smce/sm.lo: /var/www/html/smceframework2/zephir/smce/ext/smce/sm.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/smceframework2/zephir/smce/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/smceframework2/zephir/smce/ext/smce/sm.zep.c -o smce/sm.lo 
$(phplibdir)/smce.la: ./smce.la
	$(LIBTOOL) --mode=install cp ./smce.la $(phplibdir)

./smce.la: $(shared_objects_smce) $(SMCE_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_smce) $(SMCE_SHARED_LIBADD)

